### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by nicolaasuni** [jaschweder/dinesh-barcode#1]
This project is using source code copied from the project
https://github.com/tecnickcom/TCPDF originally hosted at
http://sourceforge.net/projects/tcpdf/ but all original notices about
author, copyright and license were removed or replaced.

The first commit on the copied PARENT project is indicated as 5 June
2014, so it can be safely compared against TCPDF version 6.0.083
released 29 May 2014
(https://github.com/tecnickcom/TCPDF/tree/6.0.083):

The following files appears to be almost verbatim copies of the
original ones, with the exception of the legal notices removed
(author, copyright and license):
- Datamatrix.php (include/barcodes/datamatrix.php)
- DNS1D.php (tcpdf_barcodes_1d.php)
- DNS2D.php (tcpdf_barcodes_2d.php)
- PDF417.php (include/barcodes/pdf417.php)
- QRcode.php (include/barcodes/qrcode.php)

The original code is released under the GNU LGPLv3 license and
copyrighted by Nicola Asuni - Tecnick.com LTD, but none of this
information is present in the copied files.
https://github.com/tecnickcom/TCPDF/blob/6.0.083/LICENSE.TXT

The options to remedy the infringement are:
1. immediately delete the project - this seems the best option as this project is not adding anything to the original files.
2. if the license is compatible with GNU-LGPLv3, immediately replace the infringing files with the original ones, or reinstate the original notices (author, copyright, license);
3. immediately delete the infringing files and use the new external library https://github.com/tecnickcom/tc-lib-barcode (originally based on the same TCPDF code but with tons of bug fixes and improvements).

**Comment by jaswdr** [comment]
@nicolaasuni this repo is only a fork of the original dinesh/barcode linked in packagist because the repo was deleted.
I'm not suppose to deleted this repo,I use it in some of my projects, I'll analyse your files and before that I decide what to do, I understand you, I'm a open source enthusiast and know how this is important.

regards

**Comment by jaswdr** [comment]
License details were added to the required files
